apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: gse-build-deploy-pvc-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: gse-build
      taskRef:
        name: gse-buildah-pvc-task
        kind: Task
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      params:
        - name: TLSVERIFY
          value: "false"
    
    - name: gse-apply-manifests
      taskRef:
        name: gse-apply-manifests-pvc-task
        kind: Task
      resources:
        inputs:
          - name: source
            resource: git-source
            from: [gse-build]
          - name: image
            resource: docker-image
            from: [gse-build]
      runAfter:
        - gse-build
          