apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cos-liberty
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/davemulley/test-gitops
    path: cos-liberty/dev
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cos-liberty-dev